# frozen_string_literal: true
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/questions', type: :request do
  let(:question) { Question.create!(user: user, body: 'what?') }
  let(:user) { User.create!(email: 'user@email', password: 'password') }
  let(:login) { sign_in user }

  before do
    login
    question
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      get questions_url
      expect(response).to be_successful
      expect(response.body).to have_selector('div', text: 'what?')
      expect(response.body).to have_selector('span', text: 'user@email')
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      get question_url(question)
      expect(response).to be_successful
      expect(response.body).to have_selector('div', text: 'what?')
      expect(response.body).to have_selector('span', text: 'user@email')
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_question_url
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Question' do
        expect do
          post questions_url, params: { question: { body: 'is it?' } }
        end.to change(Question, :count).by(1)
        expect(response).to redirect_to(question_url(Question.last))
        follow_redirect!
        expect(response.body).to have_selector('.notice', text: 'Question was successfully created.')
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Question' do
        expect do
          post questions_url, params: { question: { body: '' } }
        end.not_to change(Question, :count)
        expect(response).to redirect_to(new_question_url)
        follow_redirect!
        expect(response.body).to have_selector('.alert', text: "Body can't be blank")
      end
    end
  end
end
